<?php


/**
 * Interprete script
 *
 * @param string $scriptContent
 * @param integer $mode
 * @return string
 */
function interpreteScript($scriptContent, $mode = 0)
{
  // REPLACING IMPORTS AND FETCH URLS
  $devReplaceTable = [
    "api" => "./dev/api",
    "@/van" => "./src/van.js"
  ];
  // TODO: add prod replace table
  $prodReplaceTable = [
    "api" => "./dev/api",
    "@/van" => "./src/van.js"
  ];

  $replaceTable = $mode === 0 ? $devReplaceTable : $prodReplaceTable;

  $scriptContent = str_replace(array_keys($replaceTable), array_values($replaceTable), $scriptContent);

  // WARNING FOR EDITING INTERPRETED SCRIPT

  $scriptContent = "// WARNING: Please do not edit this file directly, edit it in dev/app directory instead.\n" . $scriptContent;

  return $scriptContent;
}
